# Example configuration file

model_components:
    black_hole:
        parameters:
            mass:
                desc: "log(BHmass)"
                lo: 5.0
                hi: 9.0
                step: 0.5
                fixed: true
                value: 6.0
                minstep: 0.2
                LaTeX: "$M_{BH}$"
                sformat: "%6.2f"
            radius:
                desc: "BH radius"
                lo: 0.0
                hi: 2.0
                step: 0.3
                fixed: true
                value: 1.0
                minstep: 0.1
                LaTeX: "$C$"
                sformat: "%6.2f"
        type: "Plummer"
    gas:
        parameters:
            one: 1
        type: "VisibleComponent" # class name
    stars:
        parameters:
            q:
                desc: "intrinsic flattening (C/A)"
                lo: 0.05
                hi: 0.99
                step: 0.04
                fixed: false
                value: 0.99
                minstep: 0.02
                LaTeX: "$q_{min}$"
                sformat: "%6.2f"
            p:
                desc: "intrinsic B/A"
                fixed: false
                value: 0.99
                lo: 0.99
                hi: 0.999
                step: 0.02
                minstep: 0.01
                LaTeX: "$p_{min}$"
                sformat: "%6.3f"
            u:
                desc: "sigma_obs / sigma_intrinsic"
                lo: 0.95
                hi: 1.0
                step: 0.01
                fixed: false
                value: 0.9999
                minstep: 0.01
                LaTeX: "$u_{min}$"
                sformat: "%7.4f"
        type: VisibleComponent # will need to correspond to the class name
        mge_file: "path and name"
    dark_halo:
        parameters:
            dc:
                desc: "NFW Darkmatter concentrion (in log)"
                lo: 1.5
                hi: 3.0
                step: 0.4
                fixed: false
                value: 2.0
                minstep: 0.2
                LaTeX: "$log(M_{200}/M_{star})$"
                sformat: "%6.2f"
            f:
                desc: "NFW Darkmatter fraction (in log)"
                lo: 1.5
                hi: 3.0
                step: 0.4
                fixed: false
                value: 2.0
                minstep: 0.2
                LaTeX: "$log(M_{200}/M_{star})$"
                sformat: "%6.2f"
        type: NFW

other_parameters:
    ml:
        desc: "M/L"
        lo: 0.8
        hi: 7.5
        step: 1.0
        fixed: false
        value: 3.0
        minstep: 0.5
        LaTeX: "$Y_{r}$"
        sformat: "%6.2f"
    distMPc: 38.82

orblib_settings: